import { toIsoDateTime, toVoucherDate } from '../dates';
import type { Query } from '../http-client';
import type { DateInput } from '../types';
import { BaseResource } from './base';

/** A file generated by an export, returned inside the response envelope. */
export interface ExportFile {
  filename: string;
  mimetype: string;
  base64Encoded: boolean;
  /** The file content, base64 encoded when `base64Encoded` is `true`. */
  content: string;
}

/** Progress of an export job. The job is finished once `current` reaches `total`. */
export interface ExportProgress {
  current: number;
  total: number;
}

export interface ExportJobDownloadInfo {
  filename: string;
  /** Download url of the export file. */
  link: string;
  /** Expiry date of the download url. */
  linkExpireDate: string;
}

export interface ExportConfigOptions {
  sevClientId: number;
  accountantNumber: number;
  accountantClientNumber: number;
  /** Begin of the accounting year, sent as Unix timestamp. */
  accountingYearBegin: DateInput;
}

export interface ExportDatevCsvJobOptions {
  /** Sent as Unix timestamp. */
  startDate: DateInput;
  /** Sent as Unix timestamp. */
  endDate: DateInput;
  /**
   * The models to include, given as a string of letters: `E` (earnings),
   * `X` (expenditure), `T` (transactions), `C` (cash register) and
   * `D` (assets), for example `EXTCD`.
   */
  scope: string;
  /** Includes only documents paid between `startDate` and `endDate`. Defaults to `false`. */
  exportByPaydate?: boolean;
  /** Defaults to `true`. */
  includeEnshrined?: boolean;
  /** Enshrines all exported models. Defaults to `false`. */
  enshrineDocuments?: boolean;
  /** Defaults to `false`. */
  includeDocumentImages?: boolean;
}

export interface ExportDatevXmlJobOptions {
  /** Sent as Unix timestamp. */
  startDate: DateInput;
  /** Sent as Unix timestamp. */
  endDate: DateInput;
  /**
   * The document types to include, given as a string of letters:
   * `E` (receipts, outgoing invoices and credit notes) and
   * `X` (expenditure documents), for example `EX`.
   */
  scope: string;
  /** Includes only documents paid between `startDate` and `endDate`. Defaults to `false`. */
  exportByPaydate?: boolean;
  /** Defaults to `true`. */
  includeEnshrined?: boolean;
  /** Defaults to `true`. */
  includeExportedDocuments?: boolean;
  /** Includes an XML file with the data of each document. Defaults to `true`. */
  includeDocumentXml?: boolean;
}

export type ExportInvoiceType = 'RE' | 'SR' | 'TR' | 'AR' | 'ER' | 'WKR' | 'MA';

/** Filters shared by all document exports. */
export interface ExportDocumentFilter {
  startDate?: DateInput;
  endDate?: DateInput;
  contactId?: number;
  startAmount?: number;
  endAmount?: number;
}

export interface ExportInvoiceFilter extends ExportDocumentFilter {
  /**
   * `RE` (invoice), `SR` (cancellation invoice), `TR` (partial invoice),
   * `AR` (down payment invoice), `ER` (final invoice),
   * `WKR` (recurring invoice) and `MA` (dunning).
   */
  invoiceType?: ExportInvoiceType[];
}

export interface ExportVoucherFilter extends ExportDocumentFilter {
  startPayDate?: DateInput;
  endPayDate?: DateInput;
}

export interface ExportTransactionFilter {
  paymtPurpose?: string;
  /** The name of the payee or payer. */
  name?: string;
  startDate?: DateInput;
  endDate?: DateInput;
  startAmount?: number;
  endAmount?: number;
  checkAccountId?: number;
}

export interface ExportContactFilter {
  zip?: number;
  city?: string;
  countryId?: number;
  /** Exports only organisations. */
  depth?: boolean;
  /** Exports only people. */
  onlyPeople?: boolean;
}

export interface ExportInvoicesOptions {
  download?: boolean;
  limit?: number;
  filter?: ExportInvoiceFilter;
}

export interface ExportCreditNotesOptions {
  download?: boolean;
  limit?: number;
  filter?: ExportDocumentFilter;
}

export interface ExportVouchersOptions {
  download?: boolean;
  limit?: number;
  filter?: ExportVoucherFilter;
}

export interface ExportTransactionsOptions {
  download?: boolean;
  limit?: number;
  filter?: ExportTransactionFilter;
}

export interface ExportContactsOptions {
  download?: boolean;
  limit?: number;
  filter?: ExportContactFilter;
}

/** A value of a `sevQuery` parameter before it is flattened into bracket keys. */
export type ExportSevQueryValue =
  string | number | boolean | ExportSevQueryValue[] | ExportSevQueryObject;

export interface ExportSevQueryObject {
  [key: string]: ExportSevQueryValue | undefined;
}

export interface ExportSevQueryOptions {
  modelName: string;
  limit?: number;
  filter?: ExportSevQueryObject;
}

export class ExportsResource extends BaseResource {
  /**
   * Updates the export config via `PUT /SevClient/{sevClientId}/updateExportConfig`.
   *
   * The accounting year has to be set once before any DATEV export can be run.
   */
  public async updateExportConfig(options: ExportConfigOptions): Promise<void> {
    const {
      sevClientId,
      accountantNumber,
      accountantClientNumber,
      accountingYearBegin,
    } = options;
    await this.http.request<void>({
      method: 'PUT',
      path: `/SevClient/${sevClientId}/updateExportConfig`,
      body: {
        accountantNumber,
        accountantClientNumber,
        accountingYearBegin: toVoucherDate(accountingYearBegin),
      },
    });
  }

  /** Starts a DATEV CSV zip export via `GET /Export/createDatevCsvZipExportJob` and returns the job id. */
  public createDatevCsvZipExportJob(
    options: ExportDatevCsvJobOptions,
  ): Promise<string> {
    const { startDate, endDate, ...rest } = options;
    return this.http.request<string>({
      method: 'GET',
      path: '/Export/createDatevCsvZipExportJob',
      query: {
        startDate: toVoucherDate(startDate),
        endDate: toVoucherDate(endDate),
        ...rest,
      },
    });
  }

  /** Starts a DATEV XML zip export via `GET /Export/createDatevXmlZipExportJob` and returns the job id. */
  public createDatevXmlZipExportJob(
    options: ExportDatevXmlJobOptions,
  ): Promise<string> {
    const { startDate, endDate, ...rest } = options;
    return this.http.request<string>({
      method: 'GET',
      path: '/Export/createDatevXmlZipExportJob',
      query: {
        startDate: toVoucherDate(startDate),
        endDate: toVoucherDate(endDate),
        ...rest,
      },
    });
  }

  /** Generates the hash of an export job via `GET /Progress/generateDownloadHash`. */
  public generateDownloadHash(options: {
    jobId: string;
  }): Promise<ExportProgress[]> {
    return this.http.request<ExportProgress[]>({
      method: 'GET',
      path: '/Progress/generateDownloadHash',
      query: { jobId: options.jobId },
    });
  }

  /** Retrieves the progress of an export via `GET /Progress/getProgress`. */
  public getProgress(options: { hash: string }): Promise<ExportProgress[]> {
    return this.http.request<ExportProgress[]>({
      method: 'GET',
      path: '/Progress/getProgress',
      query: { hash: options.hash },
    });
  }

  /** Retrieves the download url of a finished export job via `GET /ExportJob/jobDownloadInfo`. */
  public getJobDownloadInfo(options: {
    jobId: string;
  }): Promise<ExportJobDownloadInfo[]> {
    return this.http.request<ExportJobDownloadInfo[]>({
      method: 'GET',
      path: '/ExportJob/jobDownloadInfo',
      query: { jobId: options.jobId },
    });
  }

  /** Exports invoices as CSV via `GET /Export/invoiceCsv`. */
  public exportInvoicesCsv(
    options: ExportInvoicesOptions = {},
  ): Promise<ExportFile> {
    return this.requestExport('/Export/invoiceCsv', options, {
      modelName: 'Invoice',
      limit: options.limit,
      filter: toExportInvoiceFilter(options.filter),
    });
  }

  /** Exports invoices as zip via `GET /Export/invoiceZip`. */
  public exportInvoicesZip(
    options: ExportInvoicesOptions = {},
  ): Promise<ExportFile> {
    return this.requestExport('/Export/invoiceZip', options, {
      modelName: 'Invoice',
      limit: options.limit,
      filter: toExportInvoiceFilter(options.filter),
    });
  }

  /** Exports credit notes as CSV via `GET /Export/creditNoteCsv`. */
  public exportCreditNotesCsv(
    options: ExportCreditNotesOptions = {},
  ): Promise<ExportFile> {
    return this.requestExport('/Export/creditNoteCsv', options, {
      modelName: 'CreditNote',
      limit: options.limit,
      filter: toExportDocumentFilter(options.filter),
    });
  }

  /** Exports vouchers as CSV via `GET /Export/voucherListCsv`. */
  public exportVouchersCsv(
    options: ExportVouchersOptions = {},
  ): Promise<ExportFile> {
    return this.requestExport('/Export/voucherListCsv', options, {
      modelName: 'Voucher',
      limit: options.limit,
      filter: toExportVoucherFilter(options.filter),
    });
  }

  /** Exports vouchers as zip via `GET /Export/voucherZip`. */
  public exportVouchersZip(
    options: ExportVouchersOptions = {},
  ): Promise<ExportFile> {
    return this.requestExport('/Export/voucherZip', options, {
      modelName: 'Voucher',
      limit: options.limit,
      filter: toExportVoucherFilter(options.filter),
    });
  }

  /** Exports transactions as CSV via `GET /Export/transactionsCsv`. */
  public exportTransactionsCsv(
    options: ExportTransactionsOptions = {},
  ): Promise<ExportFile> {
    return this.requestExport('/Export/transactionsCsv', options, {
      modelName: 'CheckAccountTransaction',
      limit: options.limit,
      filter: toExportTransactionFilter(options.filter),
    });
  }

  /** Exports contacts as CSV via `GET /Export/contactListCsv`. */
  public exportContactsCsv(
    options: ExportContactsOptions = {},
  ): Promise<ExportFile> {
    return this.requestExport('/Export/contactListCsv', options, {
      modelName: 'Contact',
      limit: options.limit,
      filter: toExportContactFilter(options.filter),
    });
  }

  private requestExport(
    path: string,
    options: { download?: boolean },
    sevQuery: ExportSevQueryOptions,
  ): Promise<ExportFile> {
    return this.http.request<ExportFile>({
      method: 'GET',
      path,
      query: {
        download: options.download,
        ...toExportSevQueryParams(sevQuery),
      },
    });
  }
}

/**
 * Flattens a `sevQuery` object into the deep bracket query parameters expected
 * by the export and report endpoints, e.g. `sevQuery[filter][startDate]`.
 */
export function toExportSevQueryParams(sevQuery: ExportSevQueryOptions): Query {
  const query: Query = {};
  flattenSevQueryValue(
    'sevQuery',
    { objectName: 'SevQuery', ...sevQuery },
    query,
  );
  return query;
}

/** Maps a document export filter to its `sevQuery` representation. */
export function toExportDocumentFilter(
  filter: ExportDocumentFilter = {},
): ExportSevQueryObject {
  return {
    startDate: toOptionalIsoDateTime(filter.startDate),
    endDate: toOptionalIsoDateTime(filter.endDate),
    contact: toRef(filter.contactId, 'Contact'),
    startAmount: filter.startAmount,
    endAmount: filter.endAmount,
  };
}

/** Maps an invoice export filter to its `sevQuery` representation. */
export function toExportInvoiceFilter(
  filter: ExportInvoiceFilter = {},
): ExportSevQueryObject {
  return {
    ...toExportDocumentFilter(filter),
    invoiceType: filter.invoiceType,
  };
}

/** Maps a voucher export filter to its `sevQuery` representation. */
export function toExportVoucherFilter(
  filter: ExportVoucherFilter = {},
): ExportSevQueryObject {
  return {
    ...toExportDocumentFilter(filter),
    startPayDate: toOptionalIsoDateTime(filter.startPayDate),
    endPayDate: toOptionalIsoDateTime(filter.endPayDate),
  };
}

/** Maps a contact export filter to its `sevQuery` representation. */
export function toExportContactFilter(
  filter: ExportContactFilter = {},
): ExportSevQueryObject {
  return {
    zip: filter.zip,
    city: filter.city,
    country: toRef(filter.countryId, 'StaticCountry'),
    depth: filter.depth,
    onlyPeople: filter.onlyPeople,
  };
}

function toExportTransactionFilter(
  filter: ExportTransactionFilter = {},
): ExportSevQueryObject {
  return {
    paymtPurpose: filter.paymtPurpose,
    name: filter.name,
    startDate: toOptionalIsoDateTime(filter.startDate),
    endDate: toOptionalIsoDateTime(filter.endDate),
    startAmount: filter.startAmount,
    endAmount: filter.endAmount,
    checkAccount: toRef(filter.checkAccountId, 'CheckAccount'),
  };
}

function flattenSevQueryValue(
  key: string,
  value: ExportSevQueryValue,
  query: Query,
): void {
  if (Array.isArray(value)) {
    value.forEach((item, index) =>
      flattenSevQueryValue(`${key}[${index}]`, item, query),
    );
    return;
  }
  if (typeof value === 'object') {
    for (const [nestedKey, nestedValue] of Object.entries(value)) {
      if (nestedValue !== undefined) {
        flattenSevQueryValue(`${key}[${nestedKey}]`, nestedValue, query);
      }
    }
    return;
  }
  query[key] = value;
}

function toRef(
  id: number | undefined,
  objectName: string,
): ExportSevQueryObject | undefined {
  return id === undefined ? undefined : { id, objectName };
}

function toOptionalIsoDateTime(
  value: DateInput | undefined,
): string | undefined {
  return value === undefined ? undefined : toIsoDateTime(value);
}
